[package]
name = "wex"
version = "0.1.0"
authors = ["Arne Simon <arne_simon@gmx.de>"]
description = "REST API for the WEX market place."
license = "MIT"

[dependencies]
curl = "0.4.8"
rust-crypto = "0.2.36"
serde = "1"
serde_derive = "1"
serde_json = "1"
