[package]
name = "wex"
version = "0.1.0"
authors = ["Arne Simon <arne_simon@gmx.de>"]

[dependencies]
chrono = { version = "*", features = ["serde"] }
curl = "*"
rust-crypto = "*"
serde = "1"
serde_derive = "1"
serde_json = "1"
